spring.application.name=college-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/p001_college_management_db
spring.datasource.username=root
spring.datasource.password=8474096733

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true